### ISSUE TITLE
No test report is printed to the screen while the tests are running

### ISSUE THREAD

**Issue by somdoron** [nunit/dotnet-test-nunit#48] opened 2016-07-12 06:51 UTC
I have some tests that are hanging and hand the runner, to know which is hanging I would like to see the report of passing tests while the runner is running. Now I'm only get a report when the tests are finished and log of the failing test.

I tried to pass arguments to the console runner with -- argument separator but I get invalid argument:
![image](https://cloud.githubusercontent.com/assets/2715638/16757693/41995d04-4816-11e6-84a2-cf98cf05550b.png)

**Comment by jasonwilliams200OK** [comment] 2016-07-12 09:51
I can confirm that when we pass `dotnet test <path> -- --verbose`, we get the argument `--verbose` in `Main(string[])` which we eventually pass it to `Parse` method in `nunit/Options.cs`, where it fails to recognize the argument. Either the problem is with our `CommandLineOptions.ConfigureOptions()` or ``OptionSet.Parse(IEnumerable`1)``.

**Comment by CharliePoole** [comment] 2016-07-12 16:57
`OptionSet` is the underlying class borrowed from Mono that handles arguments for us. It should only be changed if it's absolutely necessary in order to compile for .NET core. 

Added functionality is in `CommandLineOptions`, which recognizes `--verbose` and sets a property. That property is never used anywhere that I can find. In fact, I don't think the nunit3-console runner uses it either - if it doesn't do anything, we may want to remove it and stop confusing people.

**Comment by rprouse** [comment] 2016-07-12 17:39
@somdoron, the command you want is `--labels=On`, but unfortunately, it isn't hooked up yet. I am going to close this as a duplicate of #4.

**Closed by rprouse** 2016-07-12 17:39 UTC

**Comment by rprouse** [comment] 2016-07-13 02:17
@somdoron FYI, I have implemented the `--labels` command line option and it will be in the next release, hopefully soon.

**Comment by somdoron** [comment] 2016-07-13 07:05
Thanks

**Comment by somdoron** [comment] 2016-07-18 09:26
@rprouse I released a version to nuget with a different name so I could have labels, once you release a new version I will take it off.

it is here:

https://www.nuget.org/packages/dotnet-test-nunit-with-labels

**Comment by BrainCrumbz** [comment] 2017-02-08 15:14
BTW, --labels option seems published by now
