### ISSUE TITLE
duplicated test-run element

### ISSUE THREAD

**Issue by proff** [nunit/dotnet-test-nunit#89] opened 2016-11-08 19:40 UTC
after update to beta-3 in my TestResult file element test-run is dublicated and teamcity can't parse it. In beta-2 works fine
```xml
<test-run id="0" testcasecount="107" total="107" passed="107" failed="0" inconclusive="0" skipped="0" asserts="0" result="Passed" portable-engine-version="3.3.0.0" start-time="2016-11-08 19:08:05Z" end-time="2016-11-08 19:08:40Z" duration="34.395309">
  <test-run id="0" testcasecount="107" total="107" passed="107" failed="0" inconclusive="0" skipped="0" asserts="0" result="Passed" portable-engine-version="3.3.0.0" start-time="2016-11-08 19:08:06Z" end-time="2016-11-08 19:08:40Z" duration="34.156297">
...
  </test-run>
</test-run>
```

**Comment by CharliePoole** [comment] 2016-11-08 19:42
This is a duplicate of issue #86. Please check issues before filing. :smiley:

**Closed by CharliePoole** 2016-11-08 19:42 UTC

**Comment by proff** [comment] 2016-11-08 19:54
oops :flushed:
